version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    container_name: zookeeper

  kafka:
    image: debezium/kafka:1.4
    ports:
      - 9092:9092
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    image: debezium/example-mysql:1.4
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  debezium-connect:
    image: debezium/connect:1.4
    ports:
      - 8083:8083
    container_name: connect
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - GROUP_ID=${CONNECT_GROUP_ID}
      - CONFIG_STORAGE_TOPIC=${CONNECT_CONFIG_STORAGE_TOPIC}
      - OFFSET_STORAGE_TOPIC=${CONNECT_OFFSET_STORAGE_TOPIC}
      - STATUS_STORAGE_TOPIC=${CONNECT_STATUS_STORAGE_TOPIC}
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_PRODUCER_REQUEST_TIMEOUT_MS=3000
      - CONNECT_PRODUCER_RETRY_BACKOFF_MS=500
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - mysql:mysql
    depends_on:
      - kafka
      - zookeeper
      - mysql

#  debezium-setup:
#    build: .
#    env_file:
#      - .env
#    depends_on:
#      - debezium-connect
#      - mysql
#    container_name: debezium-setup